version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - database
      - redis
    ports:
      - "8095:8095"
    container_name: dagon_server
    hostname: dagon_app
    volumes:
      - ./build:/opt/tomcat/webapps
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/dagon?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: edurootroot
      SPRING_PROFILES_ACTIVE: dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - dagon

  database:
    image: ubuntu/mysql
    container_name: dagon_db
    restart: always
    environment:
      - MYSQL_DATABASE=dagon
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=edurootroot

    ports:
      - "24306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - dagon
    hostname: dagon_database
    cap_add:
      - SYS_NICE

  redis:
    image: redis:latest
    container_name: dagon-redis-server
    networks:
      - dagon
    ports:
      - 26379:6379


networks:
  dagon:
