spring.profiles.active=@activatedProperties@
spring.application.name=dagon
app.file.upload-dir=C:/Users/edu002/IdeaProjects/dagon/uploads
app.server.base-url=https://docs.yi.or.kr:8097

spring.datasource.url=jdbc:mysql://docs.yi.or.kr:43306/dagon?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
#spring.datasource.url=jdbc:mysql://docs.yi.or.kr:24306/dagon?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=edurootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8097
# HTTPS 설정
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=your-keystore-password
server.ssl.key-alias=tomcat
jwt.secret=hello12345678901234567890123456789012345678901234567890
jwt.expiration=86400000


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.config=classpath:log4j2.xml

# swagger
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.tags-sorter=order


#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
#springdoc.swagger-ui.operations-sorter=method
#springdoc.swagger-ui.tags-sorter=alpha


spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.registration.kakao.client-name=kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.kakao.redirect-uri=http://docs.yi.or.kr:8095/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8097/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-id=a8d3170e27d32beaad8c2c4808a9a2a1
spring.security.oauth2.client.registration.kakao.client-secret=mXZJCoHYNGartnP95wvpN5Mp8MT7Qj9n
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email

# Multtae API
marine.api.base-uri=http://www.khoa.go.kr/api/oceangrid
marine.api.service-key=A093GSP9dSSMAZOfmKy4w==

tide.api.base-url=https://www.khoa.go.kr/api/oceangrid/tideObsPreTab/search.do
tide.api.service-key=A093GSP9dSSMAZOfmKy4w==
lunar.api.base-url=http://apis.data.go.kr/B090041/openapi/service/LunPhInfoService
lunar.api.service-key=MjcXfAI0zHat012HAKYfI+OkeVocaAo/LD+vybx5vmfKF3dKkUU+IXEDoz59tIlv375Z+ESYp6P788sOk5wq9A==
sun.api.base-url=http://apis.data.go.kr/B090041/openapi/service/RiseSetInfoService
sun.api.service-key=MjcXfAI0zHat012HAKYfI+OkeVocaAo/LD+vybx5vmfKF3dKkUU+IXEDoz59tIlv375Z+ESYp6P788sOk5wq9A==

# KMA ????(????) API
kma.vilagefcst.api.base-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
kma.vilagefcst.api.service-key=MjcXfAI0zHat012HAKYfI+OkeVocaAo/LD+vybx5vmfKF3dKkUU+IXEDoz59tIlv375Z+ESYp6P788sOk5wq9A==

# KMA ???? API
kma.midfcst.api.base-url=https://apis.data.go.kr/1360000/MidFcstInfoService
kma.midfcst.api.service-key=MjcXfAI0zHat012HAKYfI+OkeVocaAo/LD+vybx5vmfKF3dKkUU+IXEDoz59tIlv375Z+ESYp6P788sOk5wq9A==

# KaKao
kakao.admin=b93953a507a9c6e80e8a799fb1dcdd1c


# Swagger group

springdoc.group-configs[0].group=auth
springdoc.group-configs[0].paths-to-match=/api/auth/**,/api/users/**,/api/mypage/**,/api/oauth/**,/api/admin/login,/api/admin/register,/api/admin/users/**,/api/admin/user/{uid},/api/admin/counts,/api/partner/**,/api/partners/**,/users/**,/partner/**

springdoc.group-configs[1].group=product
springdoc.group-configs[1].paths-to-match=/api/product/**,/api/product-option/**,/api/product-fish-species/**,/api/partner/product/**,/product/**,/api/enums/**

springdoc.group-configs[2].group=fishing
springdoc.group-configs[2].paths-to-match=/api/fishing-center/**,/api/fishing-diary/**,/api/fishing-report/**,/fishing-center/diary/**,/fishing-center/report/**,/fishing/**,/api/comment/**,/api/comments/**

springdoc.group-configs[3].group=booking
springdoc.group-configs[3].paths-to-match=/api/reservation/**,/api/payments/**,/api/kakaopay/**,/payments/**,/payment/**

springdoc.group-configs[4].group=board
springdoc.group-configs[4].paths-to-match=/api/inquiries/**,/api/inquiry/**,/api/notices/**,/api/admin/notices/**,/api/faq/**,/api/admin/faq/**,/api/admin/faq-category/**,/api/event/**,/api/admin/event/**,/admin/notice/**,/admin/faq/**,/admin/faq-categories/**,/admin/event/**

springdoc.group-configs[5].group=multtae
springdoc.group-configs[5].paths-to-match=/api/multtae/**,/api/admin/station/**

springdoc.group-configs[6].group=etc
springdoc.group-configs[6].paths-to-match=/api/notifications/**,/api/admin/image/**,/api/images/**

# 파일 업로드 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=${java.io.tmpdir}
spring.servlet.multipart.resolve-lazily=false

file.upload-path=D:/dagon/uploads/products

